name: Check formatting

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y clang-format
    - name: Check formatting
      run: |
        clang-format --style=file $(git ls-files | fgrep .hpp)
        clang-format --style=file $(git ls-files | fgrep .cpp)
